# rubocop rules for footbawwl project
inherit_from: rubocop-rules.yml

# Ignore autogened code, include a couple not named *.rb
AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - bin/**/*
    - db/**/*
    - db/**/*
    - config/**/*
    - config/**/*
